<a href="https://colab.research.google.com/github/Vij-Shanker/Natural-Language-Processing/blob/main/NLP_Exp_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 2: Preprocessing

In this lab, we will be exploring how to preprocess tweets for sentiment analysis. We will provide a function for preprocessing tweets during this week's assignment, but it is still good to know what is going on under the hood. By the end of this lecture, you will see how to use the [NLTK](http://www.nltk.org) package to perform a preprocessing pipeline for Twitter datasets.

## Setup

You will be doing sentiment analysis on tweets in the first two weeks of this course. To help with that, we will be using the [Natural Language Toolkit (NLTK)](http://www.nltk.org/howto/twitter.html) package, an open-source Python library for natural language processing. It has modules for collecting, handling, and processing Twitter data, and you will be acquainted with them as we move along the course.

For this exercise, we will use a Twitter dataset that comes with NLTK. This dataset has been manually annotated and serves to establish baselines for models quickly. Let us import them now as well as a few other libraries we will be using.

In [2]:
import nltk                                # Python library for NLP
from nltk.corpus import twitter_samples    # sample Twitter dataset from NLTK
import matplotlib.pyplot as plt            # library for visualization
import random                              # pseudo-random number generator

In [ ]:
import nltk
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
text="India won the match. India celebrated victory"

In [ ]:
tokens=word_tokenize(text)
tokens

['India', 'won', 'the', 'match', '.', 'India', 'celebrated', 'victory']

In [ ]:
vocab=set(tokens)
vocab

{'.', 'India', 'celebrated', 'match', 'the', 'victory', 'won'}

In [ ]:
import re
text="India won the match in 2011"
pattern=r"[a-zA-Z0-9]+"
re.findall(pattern,text)

['India', 'won', 'the', 'match', 'in', '2011']

In [ ]:
import re
text = "The aardvaaark quickly saw a banana and aaaaan apple near the cabana."
z=[]
for text in text.split():
    pattern='a*'

    z.append(re.findall(pattern,text))
print(z)

[['', '', '', ''], ['aa', '', '', '', 'aaa', '', '', ''], ['', '', '', '', '', '', '', ''], ['', 'a', '', ''], ['a', ''], ['', 'a', '', 'a', '', 'a', ''], ['a', '', '', ''], ['aaaaa', '', ''], ['a', '', '', '', '', ''], ['', '', 'a', '', ''], ['', '', '', ''], ['', 'a', '', 'a', '', 'a', '', '']]

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.random.seed(1)

In [ ]:
a=np.random.randint(10,100,size=(7,5))
a

array([[47, 22, 82, 19, 85],
       [15, 89, 74, 26, 11],
       [86, 81, 16, 35, 60],
       [30, 28, 94, 21, 38],
       [39, 24, 60, 78, 97],
       [97, 96, 23, 19, 17],
       [73, 71, 32, 67, 11]])

In [ ]:
data=pd.DataFrame(a)
data

    0   1   2   3   4
0  47  22  82  19  85
1  15  89  74  26  11
2  86  81  16  35  60
3  30  28  94  21  38
4  39  24  60  78  97
5  97  96  23  19  17
6  73  71  32  67  11

In [ ]:
data.head(2)

    0   1   2   3   4
0  47  22  82  19  85
1  15  89  74  26  11

In [ ]:
data.iloc[3:5]

    0   1   2   3   4
3  30  28  94  21  38
4  39  24  60  78  97

In [1]:
# Experiment 2: Preprocessing

In this lab, we will be exploring how to preprocess tweets for sentiment analysis. We will provide a function for preprocessing tweets during this week's assignment, but it is still good to know what is going on under the hood. By the end of this lecture, you will see how to use the [NLTK](http://www.nltk.org) package to perform a preprocessing pipeline for Twitter datasets.

SyntaxError: unterminated string literal (detected at line 3) (968609929.py, line 3)